# Generated by Django 6.0.1 on 2026-01-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_alter_food_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='food/'),
        ),
    ]
