# Generated by Django 6.0.1 on 2026-01-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_food_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='foods/'),
        ),
    ]
